baseURL = "https://kellenfujimoto.com/"
languageCode = "en-us"
title = "Kellen Frodelius-Fujimoto"
theme = "hello-friend"
copyright = "&copy; 2018. All rights reserved."
canonifyurls = true
paginate = 10
pygmentsuseclasses = true
pygmentcodefences = true

[author]
name = "Kellen Frodelius-Fujimoto"

[blackfriday]
hrefTargetBlank = true

[taxonomies]
tag = "tags"
category = "categories"

[params]
author = "Kellen Frodelius-Fujimoto"
avatar = "avatar.jpg"
description = "Full-stack Typescript developer by day && Rust hacker by night"
homeSubtitle = "Full-stack Typescript developer"
footerCopyright = "&copy; 2019. All rights reserved."
keywords = ["rust", "typescript", "full stack", "developer"]
dateform = "2 Jan 2006"
dateformShort = "2 Jan"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02T15:04-0700"
defaultTheme = "dark"
contentTypeName = "posts"
showReadingTime = true

[[params.social]]
name = "github"
url = "https://github.com/rakenodiax"

[[params.social]]
name = "mail"
url = "mailto:kellen@kellenfujimoto.com"

[menu]
[[menu.main]]
name = "Posts"
weight = 2
identifier = "posts"
url = "/posts/"
