baseURL = "https://kellenfujimoto.com/"
languageCode = "en-us"
title = "Kellen Frodelius-Fujimoto"
theme = "hermit"
copyright = "&copy; 2018. All rights reserved."
canonifyurls = true
paginate = 10
pygmentsuseclasses = true
pygmentcodefences = true

[author]
name = "Kellen Frodelius-Fujimoto"

[blackfriday]
hrefTargetBlank = true

[taxonomies]
tag = "tags"
category = "categories"

[params]
author = "Kellen Frodelius-Fujimoto"
description = "Full-stack Typescript developer by day && Rust hacker by night"
homeSubtitle = "Full-stack Typescript • Duisburg"
footerCopyright = "&copy; 2019. All rights reserved."
keywords = ["rust", "typescript", "full stack", "developer", "duisburg"]
dateform = "2 Jan 2006"
dateformShort = "2 Jan"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02T15:04-0700"

[[params.social]]
name = "github"
url = "https://github.com/rakenodiax"

[[params.social]]
name = "email"
url = "mailto:kellen@kellenfujimoto.com"

[menu]
[[menu.main]]
name = "Posts"
weight = 2
identifier = "posts"
url = "/posts/"
[[menu.main]]
name = "Projects"
weight = 3
identifier = "projects"
url = "/projects/"
[[menu.main]]
name = "About"
weight = 4
identifier = "about"
url = "/about/"